// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: rankserver/rankserver.proto

package pb

import (
	_ "github.com/golang/protobuf/ptypes/any"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/liuwangchen/toy/transport/rpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqEcho struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqEcho) Reset() {
	*x = ReqEcho{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rankserver_rankserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqEcho) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqEcho) ProtoMessage() {}

func (x *ReqEcho) ProtoReflect() protoreflect.Message {
	mi := &file_rankserver_rankserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqEcho.ProtoReflect.Descriptor instead.
func (*ReqEcho) Descriptor() ([]byte, []int) {
	return file_rankserver_rankserver_proto_rawDescGZIP(), []int{0}
}

type RespEcho struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RespEcho) Reset() {
	*x = RespEcho{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rankserver_rankserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespEcho) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespEcho) ProtoMessage() {}

func (x *RespEcho) ProtoReflect() protoreflect.Message {
	mi := &file_rankserver_rankserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespEcho.ProtoReflect.Descriptor instead.
func (*RespEcho) Descriptor() ([]byte, []int) {
	return file_rankserver_rankserver_proto_rawDescGZIP(), []int{1}
}

var File_rankserver_rankserver_proto protoreflect.FileDescriptor

var file_rankserver_rankserver_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x61, 0x6e, 0x6b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x72, 0x61, 0x6e,
	0x6b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x20, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x45, 0x63, 0x68, 0x6f, 0x22, 0x0a, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x45, 0x63, 0x68, 0x6f, 0x32, 0x39, 0x0a, 0x0a, 0x52, 0x61, 0x6e, 0x6b, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x04, 0x45, 0x63, 0x68, 0x6f, 0x12, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x52, 0x65, 0x71, 0x45, 0x63, 0x68, 0x6f, 0x1a, 0x10, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x45, 0x63, 0x68, 0x6f, 0x22,
	0x00, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6c, 0x69, 0x75, 0x77, 0x61, 0x6e, 0x67, 0x63, 0x68, 0x65, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x73,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rankserver_rankserver_proto_rawDescOnce sync.Once
	file_rankserver_rankserver_proto_rawDescData = file_rankserver_rankserver_proto_rawDesc
)

func file_rankserver_rankserver_proto_rawDescGZIP() []byte {
	file_rankserver_rankserver_proto_rawDescOnce.Do(func() {
		file_rankserver_rankserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_rankserver_rankserver_proto_rawDescData)
	})
	return file_rankserver_rankserver_proto_rawDescData
}

var file_rankserver_rankserver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rankserver_rankserver_proto_goTypes = []interface{}{
	(*ReqEcho)(nil),  // 0: protoc.ReqEcho
	(*RespEcho)(nil), // 1: protoc.RespEcho
}
var file_rankserver_rankserver_proto_depIdxs = []int32{
	0, // 0: protoc.RankServer.Echo:input_type -> protoc.ReqEcho
	1, // 1: protoc.RankServer.Echo:output_type -> protoc.RespEcho
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rankserver_rankserver_proto_init() }
func file_rankserver_rankserver_proto_init() {
	if File_rankserver_rankserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rankserver_rankserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqEcho); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rankserver_rankserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespEcho); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rankserver_rankserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rankserver_rankserver_proto_goTypes,
		DependencyIndexes: file_rankserver_rankserver_proto_depIdxs,
		MessageInfos:      file_rankserver_rankserver_proto_msgTypes,
	}.Build()
	File_rankserver_rankserver_proto = out.File
	file_rankserver_rankserver_proto_rawDesc = nil
	file_rankserver_rankserver_proto_goTypes = nil
	file_rankserver_rankserver_proto_depIdxs = nil
}
