// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: ret.proto

package apipb

import (
	_ "github.com/golang/protobuf/ptypes/any"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/liuwangchen/toy/transport/rpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RET int32

const (
	//基本错误类型
	RET_OK                RET = 0 //ok
	RET_ERROR             RET = 1 //错误
	RET_RankTypeErr       RET = 3 // 排行榜类型错误
	RET_RankBeginInputErr RET = 4 // 初始排行输入错误
)

// Enum value maps for RET.
var (
	RET_name = map[int32]string{
		0: "OK",
		1: "ERROR",
		3: "RankTypeErr",
		4: "RankBeginInputErr",
	}
	RET_value = map[string]int32{
		"OK":                0,
		"ERROR":             1,
		"RankTypeErr":       3,
		"RankBeginInputErr": 4,
	}
)

func (x RET) Enum() *RET {
	p := new(RET)
	*p = x
	return p
}

func (x RET) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RET) Descriptor() protoreflect.EnumDescriptor {
	return file_ret_proto_enumTypes[0].Descriptor()
}

func (RET) Type() protoreflect.EnumType {
	return &file_ret_proto_enumTypes[0]
}

func (x RET) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RET.Descriptor instead.
func (RET) EnumDescriptor() ([]byte, []int) {
	return file_ret_proto_rawDescGZIP(), []int{0}
}

var File_ret_proto protoreflect.FileDescriptor

var file_ret_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x65, 0x74,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x74,
	0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x40, 0x0a, 0x03, 0x52, 0x45,
	0x54, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x61, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65,
	0x45, 0x72, 0x72, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x61, 0x6e, 0x6b, 0x42, 0x65, 0x67,
	0x69, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x45, 0x72, 0x72, 0x10, 0x04, 0x42, 0x23, 0x5a, 0x21,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x75, 0x77, 0x61,
	0x6e, 0x67, 0x63, 0x68, 0x65, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ret_proto_rawDescOnce sync.Once
	file_ret_proto_rawDescData = file_ret_proto_rawDesc
)

func file_ret_proto_rawDescGZIP() []byte {
	file_ret_proto_rawDescOnce.Do(func() {
		file_ret_proto_rawDescData = protoimpl.X.CompressGZIP(file_ret_proto_rawDescData)
	})
	return file_ret_proto_rawDescData
}

var file_ret_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ret_proto_goTypes = []interface{}{
	(RET)(0), // 0: ret.RET
}
var file_ret_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ret_proto_init() }
func file_ret_proto_init() {
	if File_ret_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ret_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ret_proto_goTypes,
		DependencyIndexes: file_ret_proto_depIdxs,
		EnumInfos:         file_ret_proto_enumTypes,
	}.Build()
	File_ret_proto = out.File
	file_ret_proto_rawDesc = nil
	file_ret_proto_goTypes = nil
	file_ret_proto_depIdxs = nil
}
